services:
  - type: web
    name: code4care-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_VISION_API_KEY
        sync: false
      - key: CORS_ALLOW_ORIGINS
        value: https://code4care.vercel.app
      - key: GEMINI_API_KEY
        sync: false
